# Generated by Django 3.2.3 on 2021-05-25 08:52

from django.db import migrations, models
import django.db.models.deletion
import trade.models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['pk'], 'verbose_name': 'manufacturer', 'verbose_name_plural': 'manufacturers'},
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(default=trade.models.Manufacturer.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='trade.manufacturer'),
        ),
    ]
